apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices

resources:
  - namespace.yaml
  - ingress.yaml
  - deployments/user-service.yaml
  - deployments/profile-service.yaml
  - deployments/order-service.yaml
  - deployments/product-service.yaml
